"""add user fields

Revision ID: 461671dd8d68
Revises: 
Create Date: 2026-05-05 18:35:41.234665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461671dd8d68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('field_of_study', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('student_index', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'student_index')
    op.drop_column('users', 'field_of_study')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
